version: '3.8'

services:
  backend:
    build: ./SITCertificate_Backend
    container_name: bun-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./SITCertificate_Frontend
    container_name: bun-frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
