FROM oven/bun:1-alpine

WORKDIR /app

COPY package.json bun.lockb* ./

RUN apk add --no-cache \
  python3 \
  make \
  g++ \
  pkgconfig \
  cairo-dev \
  pango-dev \
  jpeg-dev \
  giflib-dev

RUN bun install --frozen-lockfile

COPY . .

RUN addgroup -g 1001 -S bunjs

RUN adduser -S bunjs -u 1001

RUN chown -R bunjs:bunjs /app

USER bunjs

EXPOSE 5000

CMD ["bun", "run", "src/index.ts"]
